services:
  s3manager:
    container_name: s3manager
    build: .
    ports:
      - 7070:8080
    env_file:
      .env
    depends_on:
      - s3
    restart: always
  s3:
    container_name: s3
    image: docker.io/minio/minio
    command: server /data
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      .env
    restart: always
